// <auto-generated />
namespace Restaurant.ClassLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class twentysix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(twentysix));
        
        string IMigrationMetadata.Id
        {
            get { return "201804030554329_twentysix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
