// <auto-generated />
namespace Restaurant.ClassLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ten : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ten));
        
        string IMigrationMetadata.Id
        {
            get { return "201803021148415_ten"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
